### PR TITLE
Nette 2.4 callback compatibility

### PR DESCRIPTION
**Pull request by temistokles**

### CODE REVIEW

**Comment by jkuchar** [comment]
Firstly thanks for the PR!

I cannot merge this PR in current state because:
- this project is PHP 5.3 compatible, you cannot use $this in lambda functions; use $me = this; use ($me); ...
- this project uses tabs, not spaces

Please update you PR (force push) and I will merge it. Thanks! :-)

**Comment by jkuchar** [comment]
(don't worry about StyleCI, it is not configured properly)

**Comment by temistokles** [comment]
Thanks. You should probably rather accept d9d8c32e15f6e3d1f9ca643457a6f13c5c6b9539 which handles the same :)

**Comment by jkuchar** [comment]
Thanks! Done. :-)

**Pull request closed without merging**
