### PR TITLE
Support Nette 3.

### PR DESCRIPTION
**Pull request by radekdostal**
Please tag and release new version for Nette 3. Thx.

### CODE REVIEW

**Comment by radekdostal** [comment]
ping @jkuchar

**Comment by jkuchar** [comment]
Thanks.

**Comment by jkuchar** [comment]
Please test [this](https://github.com/jkuchar/PdfResponse/releases/tag/v0.5.0-alpha1) realease and let me know!

**Comment by radekdostal** [comment]
I had to move CSS from Latte template into a single external file. Otherwise, it works without problems on my project.

**Comment by radekdostal** [comment]
[This block of code](https://github.com/jkuchar/PdfResponse/blob/master/src/PdfResponse.php#L395) must be before [this block for adding content](https://github.com/jkuchar/PdfResponse/blob/master/src/PdfResponse.php#L389), otherwise styles defined with $pdf->styles = file_get_contents(...) are not applied.

**Comment by radekdostal** [comment]
See #25.

**Pull request merged**
