### PR TITLE
add onBeforeWrite callback

### PR DESCRIPTION
**Pull request by Twista**
introduce onBeforeCallback. 

Atm there is no way how to se Header or Footer (on every page) - because default callback is called after writeHtml

### CODE REVIEW

**Comment by jkuchar** [comment]
Thanks for PR! What is your use-case for this? Why not to simple add these data before passing reponse to sendResponse()?

**Comment by Twista** [comment]
actually for some reason it was not working. Which is weird.

example 1

```php

$pdf = new PdfResponse($template);
$pdf->getMPDF()->SetHTMLFooter("Header!");
$this->sendResponse($pdf);
```
result: not working - no header

example 2:


```php
$pdf = new PdfResponse($template);
$pdf->onBeforeWrite[] = function($mpdf){
    $mpdf->setHtmlHeader("My Header!");
    };
$this->sendResponse($pdf);
```

result: ok working


I tried to play with that for a while and try to find out why its not working (without this PR), but without any result.

**Comment by jkuchar** [comment]
Kind of hack, but why not. :-)

**Comment by Twista** [comment]
its weird, but yea. thanks!

**Pull request merged**
