### PR TITLE
composer: extend supported versions

### PR DESCRIPTION
**Pull request by radekdostal**

### CODE REVIEW

**Comment by radekdostal** [comment]
ping @jkuchar

**Comment by jkuchar** [comment]
I'm sorry. I have missed my notification.

**Review by jkuchar — APPROVED** [review]

**Comment by radekdostal** [comment]
Thank you,

**Comment by jkuchar** [comment]
Published https://github.com/jkuchar/PdfResponse/releases/tag/v0.6.2

**Pull request merged**
